FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY services/shared-py ./shared-py
COPY services/ingest-worker ./ingest-worker
COPY pyproject.toml .
COPY uv.lock .

RUN pip install --no-cache-dir ./shared-py && \
    pip install --no-cache-dir ./ingest-worker[real_structure]

CMD ["python", "-m", "ingest_worker"]
