# Copyright (c) 2025 Devayan Dewri. All rights reserved.
# Licensed under the Elastic License 2.0 - see LICENSE in the repo root.
# Commercial SaaS use is prohibited without written permission.
"""Regenerate the TypeScript verb export and VERBS.md from the Python registry."""

import json
from pathlib import Path

from shared_py.verb_registry import make_default_registry


def main() -> None:
    registry = make_default_registry()
    repo_root = Path(__file__).resolve().parent.parent

    json_path = repo_root / "packages" / "shared-types" / "src" / "verbs.generated.json"
    ts_path = repo_root / "packages" / "shared-types" / "src" / "verbs.generated.ts"
    md_path = repo_root / "VERBS.md"

    json_path.write_text(registry.to_json(), encoding="utf-8")
    md_path.write_text(registry.to_markdown(), encoding="utf-8")

    verb_ids = registry.list_ids()
    ts_content = (
        "// Generated by scripts/generate_verb_registry.py\n"
        "// Do not edit manually.\n\n"
        f"export const EDIT_VERB = {json.dumps(verb_ids, indent=2)} as const;\n"
    )
    ts_path.write_text(ts_content, encoding="utf-8")
    print(f"Wrote {json_path}")
    print(f"Wrote {ts_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
